import requests
import os
import yaml

OLLAMA_URL = "http://localhost:11434/api/generate"

# Load optional generation params from config.yaml to keep them auditable
CONFIG_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "config.yaml")
_gen_config = None
def _load_gen_config():
    global _gen_config
    if _gen_config is None:
        try:
            with open(CONFIG_PATH, "r", encoding="utf-8") as f:
                cfg = yaml.safe_load(f)
            _gen_config = cfg.get("generation", {}) if cfg else {}
        except Exception:
            _gen_config = {}
    return _gen_config

# ---------------------------------------------------------------------------
# Persistent HTTP session
# ---------------------------------------------------------------------------
# Creating a new TCP connection per Ollama request adds unnecessary latency
# (connection setup, header negotiation). A session reuses the same keep-alive
# connection across all requests. This is a safe optimization: it changes
# NO model, NO prompt, NO generation parameters, and NO outputs.
# ---------------------------------------------------------------------------
_session = requests.Session()


def generate(prompt: str, model: str) -> str:
    """
    Call local Ollama generate API.

    Args:
        prompt: The input prompt.
        model: The model name to run.

    Returns:
        The text response generated by Ollama.

    Generation parameters note
    --------------------------
    ``num_predict`` is intentionally NOT set here so that Ollama uses
    its own default (typically -1 = unlimited / model max context).
    If the benchmark is generating unexpectedly long completions,
    set ``num_predict`` explicitly in config.yaml, not here, to keep
    the configuration traceable and auditable.
    """
    payload = {
        "model": model,
        "prompt": prompt,
        "stream": False,
    }
    gen_cfg = _load_gen_config()
    if gen_cfg:
        # Ollama expects `num_predict` for max tokens; pass when configured
        if "num_predict" in gen_cfg:
            payload["num_predict"] = int(gen_cfg["num_predict"]) 
    try:
        response = _session.post(OLLAMA_URL, json=payload, timeout=300)
        response.raise_for_status()
        data = response.json()
        return data.get("response", "")
    except requests.exceptions.RequestException as e:
        raise RuntimeError(f"Ollama API request failed: {e}")
